name: release-build

# NOTE:
#  For this action to be triggered (if using the release-tag workflow)
#  you will need to ensure that the release-tag workflow is using a custom token
#  that has permission to start workflows.
#  See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Configure
        run: mkdir -p ${{ github.workspace }}/artifacts/binaries

      - name: Build uav-darwin-amd64
        run: GOARCH=amd64 GOOS=darwin go build -o ${{ github.workspace }}/artifacts/binaries/uav-darwin-amd64 -v . 
      - name: Build uav-linux-amd64
        run: GOARCH=amd64 GOOS=linux go build -o ${{ github.workspace }}/artifacts/binaries/uav-linux-amd64 -v . 
      - name: Build uav-windows-amd64
        run: GOARCH=amd64 GOOS=windows go build -o ${{ github.workspace }}/artifacts/binaries/uav-windows-amd64.exe -v .

      - uses: shogo82148/actions-upload-release-asset@v1.2.3
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/binaries/uav-darwin-amd64
      - uses: shogo82148/actions-upload-release-asset@v1.2.3
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/binaries/uav-linux-amd64
      - uses: shogo82148/actions-upload-release-asset@v1.2.3
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/binaries/uav-windows-amd64.exe

      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@2.21
        with:
          name: finbourne/uav
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # https://developer.github.com/v3/repos/releases/#get-a-release
          tags: "latest,${{ github.event.release.tag_name }}"
